version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the node code
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - script/
    - '**/*'
